### ISSUE TITLE
Sans Looped: overlapping tone signs with the vowel signs 

### ISSUE THREAD

**Issue by tassa-yoniso-manasi-karoto** [notofonts/thai#21] opened 2022-08-20 13:45 UTC
### Font 
NotoSansThaiLooped-Thin.ttf
NotoSansThaiLooped-SemiBold.ttf
NotoSansThaiLooped-Regular.ttf
NotoSansThaiLooped-Medium.ttf
NotoSansThaiLooped-Light.ttf
NotoSansThaiLooped-ExtraLight.ttf
NotoSansThaiLooped-ExtraBold.ttf
NotoSansThaiLooped-Bold.ttf
NotoSansThaiLooped-Black.ttf

### Where the font came from, and when
Site: https://fonts.google.com/noto/specimen/Noto+Sans+Thai+Looped
Date: 2022-08-20

### Font Version
v1.00

### OS name and version
Linux 5.18.17

### Application name and version
Both LibreOffice and Firefox

### Issue
  2. Observed results
This font family has overlapping tone signs with the vowel signs above consonant.
  3. Expected results
Sign tone should be above the vowel sign

### Character data
sample: ไปดูหนังเรื่องนั้นกันเถอะ

### Screenshot
![noto sans looped broken](https://user-images.githubusercontent.com/105888327/185749270-4da89410-3178-4513-9ac7-b1af8a724df3.png)

Could be related to #10

**Comment by simoncozens** [comment] 2022-08-22 07:37
This has been fixed in the sources; the version in the last Noto release [here](https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoLoopedThai) looks fine. The problem is that Google Fonts has an old build. In a sense it is related to #10 because the build failing means I cannot produce an update.

I can work around #10 by not building Looped as a variable font. I've turned the build back on, turned off variable font building, and will make a new release of Looped Thai. After that it will probably take around three or four weeks for the build to be onboarded to Google Fonts.

**Closed** 2022-08-22 10:00 UTC

**Comment by Bearfinn** [comment] 2023-03-14 04:15
Hello @simoncozens. I don't know if this is the right place, but the issue is still not fixed.

The issue is still shown in the Google Fonts website

https://fonts.google.com/noto/specimen/Noto+Sans+Thai+Looped?preview.text=%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%99%E0%B8%B5%E0%B9%88%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%84%E0%B8%AB%E0%B8%99%20%E0%B9%83%E0%B8%8A%E0%B9%88%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%A3%E0%B8%B1%E0%B8%81%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B9%80%E0%B8%9B%E0%B8%A5%E0%B9%88%E0%B8%B2&preview.text_type=custom&subset=thai&noto.script=Thai

![image](https://user-images.githubusercontent.com/17377785/224891445-9dfe28f0-1104-4e1a-be3e-528da82c2b12.png)

**Comment by simoncozens** [comment] 2023-03-14 12:36
Please see the comment above:

> This has been fixed in the sources; the version in the last Noto release [here](https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoLoopedThai) looks fine. The problem is that Google Fonts has an old build.
